version: '3'

services:
  redis:
    image: redis:6
    ports:
      - 6379:6379
    volumes:
      - ~/opt/database/redis:/data
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'me'
      MYSQL_PASSWORD: 'secret'
    ports:
      - 3306:3306
    volumes:
      - "~/opt/database/mysql:/var/lib/mysql"
