version: '3'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'me'
      MYSQL_PASSWORD: 'secret'
    ports:
      - 3306:3306
    volumes:
      - "~/opt/database/mysql:/var/lib/mysql"
